build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"


test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - mkdir -p outputs
    - echo "This is an artifact :P " > ouputs/gandalf.txt
  artifacts:
    name: gandalf
    paths:
      - outputs/gandalf.txt
    expire_in: 1 day
    when: always


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

