name: pipeline_trigger.yml

on: [push]

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'GPU')

    steps:
      - name: Trigger gitlab pipeline
        run: |
          echo Before triggering gitlab pipeline 
          echo env variable: $GITHUB_REF_NAME
          curl --request POST \
            --form token=${{secrets.TRIGGER_GITLAB_PIPELINE}} \
            --form ref=$${{github.ref_name}} \
            "https://gitlab.cern.ch/api/v4/projects/${{secrets.PROJECT_ID}}/trigger/pipeline"