name: pipeline_trigger.yml

on: [push]

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'GPU')

    steps:
      - name: Trigger gitlab pipeline
        run: |
          echo Before triggering gitlab pipeline 
#          curl --request POST \
#          --form token=${{secrets.TRIGGER_GITLAB_PIPELINE}} \
#          --form ref=main\
#         "https://gitlab.example.com/api/v4/projects/<project_id>/trigger/pipeline"