name: pipeline_trigger.yml

on: [push]

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'GPU')

    steps:
      - name: Trigger gitlab pipeline
        run: |
          echo Before triggering gitlab pipeline 
          echo env variable: $GITHUB_REF_NAME
          curl --request POST \
            --form token=${{secrets.TRIGGER_GITLAB_PIPELINE}} \
            --form ref=${{github.ref_name}} \
            "https://gitlab.cern.ch/api/v4/projects/${{secrets.PROJECT_ID}}/trigger/pipeline"

  get-gitlab-artifacts:
    runs-on: ubuntu-latest
    needs: trigger-gitlab
    steps:
      - name: requests gitlab artifacts
        run: |
          sleep 20 
          echo Before getting artifacts
          curl --request GET \
            --location \
            --include \
            --header "PRIVATE-TOKEN: ${{secrets.ARTIFACT_GITLAB_API}}" \
            --url "https://gitlab.cern.ch/api/v4/projects/${{secrets.PROJECT_ID}}/jobs/artifacts/main/raw/some/release/gandalf.txt?job=test-job2"
          cat gandalf.txt
          
    
